name: tp_film_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Ajoute la dépendance provider ici
  cupertino_icons: ^1.0.8  # Dépendance pour les icônes Cupertino
  http: ^1.2.2  # Dépendance pour les requêtes HTTP

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
